spring:
  datasource:
    url: jdbc:h2:file:./data/db-tables;MODE=ORACLE;LOCK_TIMEOUT=60000;NON_KEYWORDS=user
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-database-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2-console
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  logging:
    level:
      org.hibernate.SQL: off
      org.hibernate.type.descriptor.sql: off
